# Generated by Django 5.1.7 on 2025-03-31 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('conflito', 'Conflito')], default='pendente', max_length=20, verbose_name='Status')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_aprovadas', to='Users.customuser', verbose_name='Aprovado por')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_criadas', to='Users.customuser', verbose_name='Criado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_associadas', to='Users.customuser', verbose_name='Usuário associado')),
            ],
        ),
    ]
