# Generated by Django 5.1.7 on 2025-03-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_groups_alter_customuser_telefone_and_more'),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_associadas', to='Users.customuser', verbose_name='Usuário associado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_criadas', to='Users.customuser', verbose_name='Criado por'),
        ),
    ]
